class Generator:

    def __init__(self):
        self.target_code = ""
        self.generateHeader()

    def generateHeader(self):
        self.target_code += """
        #! /bin/vypint
        # VYPcode: 1.0
        # Generated by: xbedna73, xgajdo26

        ALIAS FP $7

        JUMP main
        """

    def generateSetNewInt(self):
        self.target_code += "SET [$SP], 0\n"
        self.target_code += "ADDI $SP, $SP, 1\n"

    def generateSetNewString(self):
        self.target_code += "CREATE $5, 1\n"
        self.target_code += "SETWORD $5, 0, \"\"\n"
        self.target_code += "GETWORD $5, $5, 0\n"
        self.target_code += "SET [$SP], $5\n"
        self.target_code += "ADDI $SP, $SP, 1\n"

    def generateSetInt(self, position, value):
        self.target_code += "SET [$FP + {}], {}\n".format(position, value)

    def generateSetString(self, position, value):
        self.target_code += "CREATE $5, 1\n"
        self.target_code += "SETWORD $5, 0, \"{}\"\n".format(value)
        self.target_code += "GETWORD $5, $5, 0\n"
        self.target_code += "SET [$FP + {}], $5\n".format(position)

    def generateSetVar(self, position1, position2):
        self.target_code += "SET [$FP + {}], [$FP + {}]\n".format(position1, position2)
